nsfw image check
Nutlope/restorePhotos pull request #14
Opened 2023-01-17 03:05 UTC by shivaylamba

This pull request is related to issue #2 - Add support for disallowing people from uploading NSFW pictures with the help of [NSFWJS](https://www.npmjs.com/package/nsfwjs) library. 

Implementation: The idea is to use this client-side library to check the file being uploaded and verify whether the image has any NSFW content in it. The NSFW model predicts the class and if the predicted class has NSFW content, the file should be stopped from getting uploaded. 

The Upload.io [React Uploader](https://www.npmjs.com/package/react-uploader) didn't have a `onValidate` hook before and I got in touch with the founder @ljwagerfield who was super quick to add the `onValidate` hook and release the feature to production in a matter of a couple of hours (now that is quick product delivery!) 

Using the `onValidate` hook and the `NSFWPredictor.isSafeImg()` in case there is a file that is not safe, it will not get uploaded to UploadIo and the user will receive a message stating "Detected an NSFW image"

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19529592/212800264-415feeb4-d920-4985-a69d-8d32daa8d229.png">

Previously before the `onValidate` hook was added to the Upload-io uploader, I was using a Tailwind Class to showcase an error for the detection of NSFW images. I can still add that if you think it is needed @Nutlope 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/19529592/212800534-128f358d-3a79-4a85-ac3b-a6146a8e7d97.png">

About the model: The ML model files (the model weights + model.json ) are currently hosted on an AWS S3 bucket, if needed I can share those with you and you could host them on Upload.io. Let me know if that works. The model URL is used in the `nsfwCheck.ts` file. 
```
'https://nsfw-model-1.s3.us-west-2.amazonaws.com/nsfw-predict-model/',
```

2023-01-17 10:56 UTC, ljwagerfield commented
This is great work @shivaylamba 🎉 

We're looking into adding NSFW filtering server-side to Upload.io later this year, and this is an excellent stopgap solution.

Thank you again for the feature suggestion re. `onValidate: file => Promise<string | undefined>` for async custom file validation pre-upload 💪 

All the best!

2023-01-17 11:00 UTC, ljwagerfield commented on pages/restore.tsx
> +      console.log("NSFW predictor threw an error");
```suggestion
      console.error("NSFW predictor threw an error", error);
```

2023-01-17 11:00 UTC, ljwagerfield commented on pages/restore.tsx
> +  onValidate: async (file: any): Promise<undefined | string> => {
```suggestion
  onValidate: async (file: File): Promise<undefined | string> => {
```

2023-01-18 18:00 UTC, 360macky commented on utils/nsfwCheck.ts
> +    console.log(predictions);
NIT: Hi @shivaylamba! There is a `console.log` in the `classPredictor` function

2023-01-20 18:38 UTC, llegomark commented
I have tested the NSFW image check on my website, https://restorephotos.app/, and it appears to be functioning properly.
![Screenshot (115)](https://user-images.githubusercontent.com/111579522/213779484-5fa6cb8b-2691-49a1-a02f-2519fc73f93b.png)

2023-01-20 18:53 UTC, llegomark commented
![Web capture_21-1-2023_25156_github com](https://user-images.githubusercontent.com/111579522/213782116-122f8cd3-a493-4baf-a612-e3b4657c1378.jpeg)
![Web capture_21-1-2023_25226_github com](https://user-images.githubusercontent.com/111579522/213782124-77dea8b5-cff0-4f28-9ad9-4593bf395d6c.jpeg)
![Web capture_21-1-2023_25210_github com](https://user-images.githubusercontent.com/111579522/213782127-edafee07-6cd7-45fa-9ac0-ea87771b36b7.jpeg)

2023-01-20 19:03 UTC, llegomark requested changes
Great work on implementing the NSFW image check feature! However, I have noticed that there are some issues with false positives where pictures of white people or those that appear bright are being incorrectly tagged as NSFW. Can you please look into this and see if there is a way to improve the accuracy of the algorithm? Thank you!

2023-02-04 04:17 UTC, Nutlope commented
Excellent work @shivaylamba, I'd like to merge this. Mind addressing the conflicts and we can get it merged?

2023-02-20 06:54 UTC, Nutlope commented
This is now merged as a part of #24. Thanks all!

2023-02-20 06:54 UTC, closed without merging